{ * ************************************************************************ * }
{ *                              SolLib Library                              * }
{ *                       Author - Ugochukwu Mmaduekwe                       * }
{ *              Github Repository <https://github.com/Xor-el>               * }
{ *                                                                          * }
{ *  Distributed under the MIT software license, see the accompanying file   * }
{ *                                 LICENSE                                  * }
{ *         or visit http://www.opensource.org/licenses/mit-license.         * }
{ *                                                                          * }
{ *                            Acknowledgements:                             * }
{ *                                                                          * }
{ *  Thanks to InstallAware (https://www.installaware.com/) for sponsoring   * }
{ *                     the development of this library                      * }
{ * ************************************************************************ * }

(* &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& *)

unit SlpSolLibExceptions;

{$I ../Include/SolLib.inc}

interface

uses
  System.SysUtils,
  SlpRequestResult,
  SlpRpcMessage;

type
  /// <summary>
  /// An exception thrown brown the TokenWallet that includes the failing RPC call
  /// </summary>
  ETokenWalletException<T> = class(Exception)
  private
    FRequestResult: IRequestResult<T>;
  public
    /// <summary>
    /// The failing RequestResult that caused the Exception
    /// </summary>
    property RequestResult: IRequestResult<T> read FRequestResult;

    /// <summary>
    /// An Exception generated by an RPC failure within the TokenWallet
    /// </summary>
    /// <param name="AMessage">The exception message</param>
    /// <param name="AFailedResult">The failing RequestResult that caused the exception</param>
    constructor Create(const AMessage: string;
      const AFailedResult: IRequestResult<T>);
  end;

  type
  /// <summary>
  /// Exception thrown during decryption operations
  /// </summary>
  EDecryptionException = class(Exception)
  public
    /// <summary>
    /// Create a new decryption exception
    /// </summary>
    /// <param name="AMsg">The exception message</param>
    constructor Create(const AMsg: string);
  end;

  /// <summary>
  /// Exception thrown when KDF type is invalid
  /// </summary>
  EInvalidKdfException = class(Exception)
  public
    /// <summary>
    /// Create a new invalid KDF exception
    /// </summary>
    /// <param name="AKdf">The invalid KDF string</param>
    constructor Create(const AKdf: string);
  end;

  type
  /// <summary>Encapsulates the batch request failure that is relayed to all callbacks.</summary>
  EBatchRequestException = class(Exception)
  private
    FRpcResult: IRequestResult<TJsonRpcBatchResponse>;
  public
    constructor Create(const ARpcResult: IRequestResult<TJsonRpcBatchResponse>);

    property RpcResult: IRequestResult<TJsonRpcBatchResponse> read FRpcResult;
  end;

 type
  EKdNormalizationNotSupported = class(ENotSupportedException);

  type
   ETokenMintResolveException = class(Exception);

  type
  /// <summary>
  /// Error raised when compute-budget estimation cannot be completed.
  /// </summary>
  EComputeBudgetEstimationError = class(Exception);

  EInvalidProgramException = class(Exception);

implementation

{ ETokenWalletException<T> }

constructor ETokenWalletException<T>.Create(const AMessage: string;
  const AFailedResult: IRequestResult<T>);
begin
  inherited Create(&Message);
  FRequestResult := AFailedResult;
end;

{ EDecryptionException }

constructor EDecryptionException.Create(const AMsg: string);
begin
  inherited Create(AMsg);
end;

{ EInvalidKdfException }

constructor EInvalidKdfException.Create(const AKdf: string);
begin
  inherited Create('Invalid kdf: ' + AKdf);
end;

{ EBatchRequestException }

constructor EBatchRequestException.Create(const ARpcResult
  : IRequestResult<TJsonRpcBatchResponse>);
begin
  inherited Create('Batch request failure - ' + ARpcResult.Reason);
  FRpcResult := ARpcResult;
end;

end.
